apiVersion: v1
kind: Pod
metadata:
  name: getcert
  labels:
    app: getcert
spec:
  containers:
  - name: getcert
    image: neha16/getcert1:latest
    imagePullPolicy: Always  # or IfNotPresent
    volumeMounts:
        - name: spire-agent-socket
          mountPath: /run/spire/sockets
        - name: spire-admin-socket
          mountPath: /run/spire/sockets-admin
  volumes:
    - name: spire-agent-socket
      hostPath:
        path: /run/spire/sockets
        type: Directory
    - name: spire-admin-socket
      hostPath:
        path: /run/spire/sockets-admin
        type: DirectoryOrCreate
    